### PR TITLE
Add direct documentation linking

### PR DESCRIPTION
**Pull request by ScruffyRules**

### CODE REVIEW

**Comment by ScruffyRules** [comment]
How so?

**Comment by aliasfalse** [comment]
probably just looked like it, like i said, it looked good overall. I think the commenting was heavy, but it's good to have.

**Comment by aliasfalse** [comment]
on, and you spelled `onclick` as `onclik`

**Comment by ScruffyRules** [comment]
That is intended, I'm pretty sure it breaks when it's `onclick`

**Comment by aliasfalse** [comment]
it shouldn't... oh well, i can toy with it later, wanna figure out linking in js and images so the html isn't so bloated.

**Comment by ScruffyRules** [comment]
Just tested then, it breaks when it's `onclick`

**Pull request merged**
